# Generated by Django 4.2.1 on 2023-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=250)),
                ('processor', models.CharField(max_length=250)),
                ('storage', models.CharField(max_length=250)),
                ('battery', models.CharField(max_length=150)),
                ('ram', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=250)),
            ],
        ),
    ]
